apiVersion: v1
kind: Secret
metadata:
  name: expensy-secrets
  namespace: default
type: Opaque
stringData:
  REDIS_PASSWORD: "CHANGE_ME"
  MONGO_USERNAME: "CHANGE_ME"
  MONGO_PASSWORD: "CHANGE_ME"
  DATABASE_URI: "mongodb://CHANGE_ME:CHANGE_ME@mongo-service:27017/"